--Crie uma tabela aluno com as colunas matrícula e nome.
--Depois crie um trigger que não permita o cadastro de alunos cujo nome começa com a letra “a”.

CREATE TABLE ALUNO (
	MATRICULA INT PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL
);

CREATE FUNCTION FUNCAO_PROIBE() RETURNS TRIGGER AS $$
BEGIN
	IF (NEW.NOME ILIKE 'A%') THEN
		RAISE EXCEPTION 'NÃO É PERMITIDO CADASTRO DE ALUNOS QUE O NOME COMEÇA COMA LETRA A';
	END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER PROIBE_LETRA_A BEFORE INSERT ON ALUNO
FOR EACH ROW EXECUTE PROCEDURE FUNCAO_PROIBE();

INSERT INTO ALUNO VALUES (1, 'AMANDA');
INSERT INTO ALUNO VALUES (1, 'VITORIA');
-- DÚVIDA, SE A INSERÇÃO FOR DE VÁRIAS LINHAS E LANÇAR UM ERRO AS OUTRAS LINHAS DE BAIXO NÃO SÃO EXECUTADAS.

-- Primeiro crie uma tabela chamada Funcionário com os seguintes campos: código (int), nome (varchar(30)), salário
-- (int), data_última_atualização (timestamp), usuário_que_atualizou (varchar(30)). Na inserção desta
-- tabela, você deve informar apenas o código, nome e salário do funcionário. Agora crie um Trigger que não permita o nome
-- nulo, a salário nulo e nem negativo.

CREATE TABLE FUNCIONARIO(
	CODIGO INT PRIMARY KEY,
	NOME VARCHAR(30),
	SALARIO INT,
	DT_ULTIMA_ATUALIZACAO TIMESTAMP,
	USUARIO_ATUALIZOU VARCHAR(30)	
);

CREATE FUNCTION PROIBE_NULOS() RETURNS TRIGGER AS $$
BEGIN
	IF(NEW.NOME IS NULL) THEN
		RAISE EXCEPTION 'O nome do funcionário não pode ser nulo';
	END IF;
	IF(NEW.SALARIO IS NULL) THEN 
		RAISE EXCEPTION 'O salário do funcionário não pode ser nulo';
	END IF;
	IF(NEW.SALARIO <= 0) THEN
		RAISE EXCEPTION 'O salário do funcionário não pode ser negativo nem 0.';
		END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER CAMPOS_VALIDOS BEFORE INSERT ON FUNCIONARIO
FOR EACH ROW EXECUTE PROCEDURE PROIBE_NULOS();

INSERT INTO FUNCIONARIO(CODIGO) VALUES (1);
INSERT INTO FUNCIONARIO(CODIGO, NOME, SALARIO) VALUES (1, 'VITORIA', NULL);
INSERT INTO FUNCIONARIO(CODIGO, NOME, SALARIO) VALUES (1, NULL, 2000);
INSERT INTO FUNCIONARIO(CODIGO, NOME, SALARIO) VALUES (1, 'VITORIA', 0);
INSERT INTO FUNCIONARIO(CODIGO, NOME, SALARIO) VALUES (1, 'VITORIA', 1518);

-- Agora crie uma tabela chamada Empregado com os atributos nome e salário. Crie também outra tabela chamada
-- Empregado_auditoria com os atributos: operação (char(1)), usuário (varchar), data (timestamp), nome (varchar), salário
-- (integer) . Agora crie um trigger que registre na tabela Empregado_auditoria a modificação que foi feita na tabela
-- empregado (E,A,I), quem fez a modificação, a data da modificação, o nome do empregado que foi alterado e o salário
-- atual dele.

CREATE TABLE EMPREGADO (
	CODIGO INT PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
	SALARIO FLOAT NOT NULL
);

CREATE TABLE EMPREGADO_AUDITORIA (
	CODIGO SERIAL PRIMARY KEY,
	OPERACAO CHAR(1) NOT NULL,
	USUARIO VARCHAR(15) NOT NULL,
	DATA_OP TIMESTAMP NOT NULL,
	NOME VARCHAR(20) NOT NULL,
	SALARIO FLOAT NOT NULL
)

CREATE OR REPLACE FUNCTION FUNCAO_REGISTRA() RETURNS TRIGGER AS $$
BEGIN
	IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
		INSERT INTO EMPREGADO_AUDITORIA VALUES (DEFAULT, SUBSTR(TG_OP, 1, 1), CURRENT_USER, NOW(), NEW.NOME, NEW.SALARIO);
		RETURN NEW;
	END IF;
	IF (TG_OP = 'DELETE') THEN
		INSERT INTO EMPREGADO_AUDITORIA VALUES (DEFAULT, 'D', CURRENT_USER, NOW(), OLD.NOME, OLD.SALARIO);
		RETURN OLD;
	END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER REGISTRA_ALTERACAO AFTER INSERT OR UPDATE OR DELETE ON EMPREGADO
FOR EACH ROW EXECUTE PROCEDURE FUNCAO_REGISTRA();

DROP TRIGGER REGISTRA_ALTERACAO ON EMPREGADO

INSERT INTO EMPREGADO VALUES (2, 'JULIA', 1518);
UPDATE EMPREGADO SET SALARIO = 2000 WHERE CODIGO = 1;
DELETE FROM EMPREGADO WHERE CODIGO = 2;

SELECT * FROM EMPREGADO_AUDITORIA;
SELECT * FROM EMPREGADO

-- DUVÍDA, QUANDO ALGO DÁ ERRO NO TRIGGER MESMO QUE SEJA DEPOIS DA OPERAÇÃO, A OPERAÇÃO NÃO É CONCLUIDA, COMO SE FOSSE UMA TRANSAÇÃO.

-- Crie a tabela Empregado2 com os atributos código (serial e chave primária), nome (varchar) e salário (integer). Crie
-- também a tabela Empregado2_audit com os seguintes atributos: usuário (varchar), data (timestamp), id (integer),
-- coluna (text), valor_antigo (text), valor_novo(text). Agora crie um trigger que não permita a alteração da chave primária e
-- insira registros na tabela Empregado2_audit para refletir as alterações realizadas na tabela Empregado2.

CREATE TABLE EMPREGADO2 (
	CODIGO SERIAL PRIMARY KEY,
	NOME VARCHAR(20),
	SALARIO INT
);

CREATE TABLE EMPREGADO2_AUDIT (
	USUARIO VARCHAR(20), 
	DT_ATUALIZACAO TIMESTAMP,
	CODIGO INT,
	COLUNA VARCHAR(20),
	VALOR_ANTIGO VARCHAR(20),
	VALOR_NOVO VARCHAR(20)
);

CREATE FUNCTION FUNCAO_AUDIT() RETURNS TRIGGER AS $$
BEGIN
	IF (NEW.CODIGO <> OLD.CODIGO) THEN
		RAISE EXCEPTION 'Não é permitido alterar a chave primária da tabela empregado2.';
	END IF;
	IF (NEW.NOME IS DISTINCT FROM OLD.NOME) THEN
		INSERT INTO EMPREGADO2_AUDIT VALUES (CURRENT_USER, NOW(), NEW.CODIGO, 'NOME', OLD.NOME, NEW.NOME);
	END IF;
	IF (NEW.SALARIO IS DISTINCT FROM OLD.SALARIO) THEN
		INSERT INTO EMPREGADO2_AUDIT VALUES (CURRENT_USER, NOW(), NEW.CODIGO, 'SALARIO', OLD.SALARIO, NEW.SALARIO);
	END IF;
	RETURN NEW;
END
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER REGISTRA_UPDATE AFTER UPDATE ON EMPREGADO2
FOR EACH ROW EXECUTE PROCEDURE FUNCAO_AUDIT();

SELECT * FROM EMPREGADO2_AUDIT;

INSERT INTO EMPREGADO2 VALUES (DEFAULT, 'VITORIA', 1300);
UPDATE EMPREGADO2 SET CODIGO = 2 WHERE CODIGO = 1;
UPDATE EMPREGADO2 SET NOME = 'JULIA', SALARIO = 2000 WHERE CODIGO = 1;
UPDATE EMPREGADO2 SET NOME = 'JOANA' WHERE CODIGO = 1;
UPDATE EMPREGADO2 SET  SALARIO = 7000 WHERE CODIGO = 1;