CREATE TABLE CATEGORIA(
COD_CAT SERIAL PRIMARY KEY,
NOME VARCHAR(20) NOT NULL,
VALOR_DIA NUMERIC NOT NULL
);

CREATE TABLE APTO(
NUM INT NOT NULL,
STATUS CHAR(1) NOT NULL CHECK(STATUS = 'O' OR STATUS = 'D'),
COD_CAT INT NULL REFERENCES CATEGORIA(COD_CAT),

PRIMARY KEY(NUM)
);

CREATE TABLE HOSPEDE(
COD_HOSP SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DT_NASC DATE 
);

CREATE TABLE FUNCIONARIO(
COD_FUNC SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DT_NASC DATE
);

CREATE TABLE HOSPEDAGEM(
COD_HOSPEDAGEM SERIAL PRIMARY KEY,
DT_ENT DATE NOT NULL,
DT_SAIDA DATE,
VALOR_TOTAL FLOAT,
COD_HOSP INT REFERENCES HOSPEDE(COD_HOSP),
NUM_QUARTO INT REFERENCES APTO(NUM),
COD_FUNC INT REFERENCES FUNCIONARIO(COD_FUNC)
);

CREATE TABLE RESERVA(
COD_RESERVA SERIAL PRIMARY KEY,
DT_PREV_ENT DATE NOT NULL,
DT_PREV_SAIDA DATE NOT NULL,
COD_HOSP INT REFERENCES HOSPEDE(COD_HOSP),
NUM_QUARTO INT REFERENCES APTO(NUM),
COD_FUNC INT REFERENCES FUNCIONARIO(COD_FUNC)
);

INSERT INTO CATEGORIA(nome, valor_dia) 
VALUES ('PADRÃO', 300.00),
	    ('LUXO', 400.00);

INSERT INTO APTO(num, status, cod_cat)
VALUES (100, 'D', 1),
       (200, 'D', 2);

INSERT INTO CATEGORIA(nome, valor_dia) 
VALUES ('PRESIDENCIAL', 700.00),
	   ('COBERTURA', 800.00);

INSERT INTO APTO(num, status, cod_cat)
VALUES (300, 'D', 3),
       (400, 'D', 4);

INSERT INTO HOSPEDE(nome, dt_nasc)
VALUES
	('Thalisson', '2004-05-24'),
	('Claudenes', '1978-08-16'),
	('Jardel Júnior', '2006-11-02');