-- JOIN 05/03

-- Nome doshóspedes que se hospedaram em 2026
-- SINTAXE 1:
SELECT H.NOME FROM HOSPEDE H, HOSPEDAGEM HO
WHERE H.COD_HOSP = HO.COD_HOSP
AND EXTRACT(YEAR FROM DT_ENT) = 2026;

-- Nome dos hospedes atendidos pela funcionária Claudia
-- SINTAXE 2:
SELECT HO.NOME FROM FUNCIONARIO F
JOIN HOSPEDAGEM H
ON F.COD_FUNC = H.COD_FUNC
JOIN HOSPEDE HO
ON H.COD_HOSP = HO.COD_HOSP
WHERE F.NOME = 'Claudia';

-- Nome das categorias que não têm apartamentos
SELECT NOME FROM CATEGORIA C
LEFT JOIN APTO A
ON C.COD_CAT = A.COD_CAT 
WHERE NUM IS NULL;

-- Obtenha o nome dos funcionários que nunca hospedaram o hóspede Thalisson.
SELECT F.NOME FROM
FUNCIONARIO F 
WHERE F.COD_FUNC NOT IN
(SELECT COD_FUNC FROM HOSPEDAGEM H 
JOIN HOSPEDE HO
ON H.COD_HOSP = HO.COD_HOSP
WHERE HO.NOME = 'Thalisson');

-- ou USANDO SOMENTE JOIN:

SELECT F.NOME FROM FUNCIONARIO F
LEFT JOIN (
SELECT COD_FUNC FROM HOSPEDAGEM H 
JOIN HOSPEDE HO
ON H.COD_HOSP = HO.COD_HOSP
WHERE HO.NOME = 'Thalisson') AS A
ON F.COD_FUNC = A.COD_FUNC
WHERE A.COD_FUNC IS NULL;