-- TRIGGERS

-- NÃO PERMITA QUE UM MESMO HÓSPEDE POSSUA MAIS DE UMA HOSPEDAGEM ATIVA AO MESMO TEMPO.
CREATE FUNCTION PROIBE_HOSPEDAGEM() RETURNS TRIGGER AS $$
BEGIN
IF NEW.COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDAGEM WHERE DT_SAIDA IS NULL) THEN
	RAISE EXCEPTION 'Esse hóspede já possui uma hospedagem ativa.';
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER CHECA_HOSPEDE BEFORE INSERT ON HOSPEDAGEM
FOR EACH ROW EXECUTE PROCEDURE PROIBE_HOSPEDAGEM();

INSERT INTO HOSPEDAGEM(DT_ENT, COD_HOSP, NUM_QUARTO, COD_FUNC) 
VALUES('2026-02-02', 1, 100, 1);

-- SEMPRE QUE UM HÓSPEDE SAIR DO HOTEL (PREENCHER A DATA DE SAÍDA), DEVE SER
--CALCULADO O VALOR TOTAL E ALTERADO O STATUS DO APARTAMENTO;

CREATE OR REPLACE FUNCTION FUNCAO_CHECKOUT() RETURNS TRIGGER AS $$
BEGIN
IF (OLD.DT_SAIDA IS NULL AND NEW.DT_SAIDA IS NOT NULL) THEN
	UPDATE HOSPEDAGEM SET VALOR_TOTAL = (DT_SAIDA - DT_ENT) * (SELECT VALOR_DIA FROM CATEGORIA WHERE
	COD_CAT IN(SELECT COD_CAT FROM APTO WHERE NUM IN
	(SELECT NUM_QUARTO FROM HOSPEDAGEM WHERE COD_HOSPEDAGEM = OLD.COD_HOSPEDAGEM)))
	WHERE COD_HOSPEDAGEM = OLD.COD_HOSPEDAGEM;
	UPDATE APTO SET STATUS = 'D' WHERE NUM = OLD.NUM_QUARTO;
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER CHECKOUT_HOSPEDE AFTER UPDATE ON HOSPEDAGEM 
FOR EACH ROW EXECUTE PROCEDURE FUNCAO_CHECKOUT();

UPDATE HOSPEDAGEM SET DT_SAIDA = '2026-02-18' WHERE COD_HOSPEDAGEM = 5;

SELECT * FROM HOSPEDAGEM
SELECT * FROM APTO

