CREATE TABLE VENDAS (
COD_VENDA SERIAL PRIMARY KEY,
NOME_VENDEDOR VARCHAR(20) NOT NULL,
DATA_VENDA DATE NOT NULL,
VALOR_VENDIDO FLOAT NOT NULL
)

INSERT INTO VENDAS(nome_vendedor, data_venda, valor_vendido)
VALUES
('vitoria', '2026-03-08', 100),
('vitoria', '2026-03-08', 100),
('thalisson', '2026-03-02', 200),
('junior', '2026-03-03', 400),
('thiago', '2026-03-01', 50),
('thiago', '2026-03-01', 50),
('thiago', '2026-03-01', 50),
('thiago', '2026-03-01', 50),
('thiago', '2026-03-01', 50),
('thiago', '2026-03-01', 50)

-- Mostre o nome dos vendedores que venderam mais de X reais no mês de março de 2024.
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) AS TOTAL_VENDIDO FROM VENDAS
GROUP BY NOME_VENDEDOR HAVING SUM(VALOR_VENDIDO) > 200;

-- Mostre o nome de um dos vendedores que mais vendeu no mês de março de 2024.
SELECT NOME_VENDEDOR AS TOTAL_VENDIDO FROM VENDAS WHERE 
EXTRACT(YEAR FROM DATA_VENDA) = 2026 
AND EXTRACT(MONTH FROM DATA_VENDA) = 03
GROUP BY NOME_VENDEDOR 
ORDER BY TOTAL_VENDIDO DESC
LIMIT 1;

-- Sem usar select na cláusula from, qual o nome do(s) vendedor(es) que mais vendeu no mês de março de 2024?
CREATE VIEW VENDAS_MARCO_2026 AS
SELECT NOME_VENDEDOR, SUM(VALOR_VENDIDO) AS TOTAL_VENDIDO 
FROM VENDAS WHERE 
EXTRACT(YEAR FROM DATA_VENDA) = 2026 
AND EXTRACT(MONTH FROM DATA_VENDA) = 03
GROUP BY NOME_VENDEDOR 
ORDER BY TOTAL_VENDIDO DESC;

SELECT NOME_VENDEDOR FROM VENDAS_MARCO_2026
WHERE TOTAL_VENDIDO = (SELECT MAX(TOTAL_VENDIDO) FROM VENDAS_MARCO_2026);